/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* eslint-disable */
//@ts-ignore
//@ts-nocheck
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function HotDog(props) {
  const { nodes, materials } = useGLTF('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/hotDog.glb')
  return (
    <RigidBody
      position={props.position}
      colliders={'cuboid'}
      type={'fixed'}
      sensor={true}
      canSleep={false}
      enabledRotations={[false, false, false]}
      name={'hotdog'}
      onIntersectionEnter={({ manifold, target, other }) => {
        console.log('Collision at world position ', manifold.solverContactPoint(0))

        if (other.rigidBodyObject) {
          console.log(
            // this rigid body's Object3D
            target.rigidBodyObject.name,
            ' collided with ',
            // the other rigid body's Object3D
            other.rigidBodyObject.name
          )
        }
      }}>
      <group rotation={props.rotation} position={props.objPosition} dispose={null}>
        <mesh castShadow receiveShadow geometry={nodes.hotDog.geometry} material={materials.brownLight}>
          <group position={[0, 0.14, 0]} rotation={[Math.PI, 0, -Math.PI]}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh_sauce.geometry} material={materials.yellow} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh_sauce_1.geometry} material={materials.red} />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.sausage.geometry}
            material={materials.brown}
            position={[-0.293, 0.092, 0]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.93}
          />
        </mesh>
      </group>
    </RigidBody>
  )
}

useGLTF.preload('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/hotDog.glb')
