/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* eslint-disable */
//@ts-ignore
//@ts-nocheck
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SimpleHotDog(props) {
  const { nodes, materials } = useGLTF('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/hotDog.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.hotDog.geometry} material={materials.brownLight}>
        <group position={[0, 0.14, 0]} rotation={[Math.PI, 0, -Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh_sauce.geometry} material={materials.yellow} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_sauce_1.geometry} material={materials.red} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sausage.geometry}
          material={materials.brown}
          position={[-0.293, 0.092, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.93}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/hotDog.glb')
