/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* eslint-disable */
//@ts-ignore
//@ts-nocheck
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SimpleWineRed(props) {
  const { nodes, materials } = useGLTF('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/wineRed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineRed.geometry} material={materials.brownDarkest} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineRed_1.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineRed_2.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineRed_3.geometry} material={materials.red} />
    </group>
  )
}

useGLTF.preload('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/wineRed.glb')
