/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* eslint-disable */
//@ts-ignore
//@ts-nocheck
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SimplePizza(props) {
  const { nodes, materials } = useGLTF('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/pizza.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group rotation={[0, Math.PI / 2, 0]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group rotation={[0, Math.PI / 4, 0]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group rotation={[0, -Math.PI / 4, 0]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group rotation={[0, -Math.PI / 2, 0]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
      <group rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={[0.69, 0.869, 0.69]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_1.geometry} material={materials.yellow} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_2.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_3.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_slice3_4.geometry} material={materials.green} />
      </group>
    </group>
  )
}

useGLTF.preload('https://gwcjylrsyylsuacdrnov.supabase.co/storage/v1/object/public/game/pizza.glb')
